variable "name" {}
variable "instance_type" {}
variable "env" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "subnets" {}
variable "bastion" {}
variable "port_number" {}
variable "allow_app" {}
variable "vpc_id" {}
variable "lb_dns_name" {}